using SalesSystem.Domain.Accounting.Entities;
using SalesSystem.Domain.Common;
using SalesSystem.Domain.Enums;
using SalesSystem.Domain.Exceptions;

namespace SalesSystem.Domain.Entities;

/// <summary>
/// Represents an inventory adjustment operation that corrects stock levels
/// (surplus or shortage) and creates offsetting journal entries.
/// Adjustments are irreversible once posted.
/// </summary>
public class InventoryAdjustment : DocumentEntity
{
    public int AdjustmentNo { get; private set; }
    public DateTime AdjustmentDate { get; private set; }
    public short WarehouseId { get; private set; }
    public InventoryAdjustmentType AdjustmentType { get; private set; }

    /// <summary>
    /// The offset account used for the journal entry side of the adjustment
    /// (e.g., inventory adjustment expense or income account).
    /// </summary>
    public int AccountId { get; private set; }

    public InventoryCountStatus Status { get; private set; }
    public int? PostedByUserId { get; private set; }

    /// <summary>سبب التسوية (مثال: تلف، انتهاء صلاحية، خطأ في الجرد)</summary>
    public string? Reason { get; private set; }

    /// <summary>نوع المرجع المرتبط (مثال: InventoryCount, etc.)</summary>
    public string? ReferenceType { get; private set; }

    /// <summary>معرف المرجع المرتبط</summary>
    public int? ReferenceId { get; private set; }

    public string? Notes { get; private set; }

    // Navigation properties
    public virtual Warehouse? Warehouse { get; private set; }
    public virtual Account? Account { get; private set; }
    public virtual User? PostedByUser { get; private set; }

    private readonly List<InventoryAdjustmentLine> _lines = new();
    public IReadOnlyCollection<InventoryAdjustmentLine> Lines => _lines.AsReadOnly();

    private InventoryAdjustment() { }

    /// <summary>
    /// Creates a new inventory adjustment.
    /// </summary>
    /// <param name="adjustmentNo">The sequential adjustment number (generated by DocumentSequenceService).</param>
    /// <param name="warehouseId">The warehouse where the adjustment occurs.</param>
    /// <param name="adjustmentDate">The date of the adjustment.</param>
    /// <param name="adjustmentType">Addition, Deduction, or Correction.</param>
    /// <param name="accountId">The offset account for journal entry.</param>
    /// <param name="createdByUserId">Optional ID of the user creating the adjustment.</param>
    /// <param name="reason">Optional reason for the adjustment.</param>
    /// <param name="referenceType">Optional reference type (e.g., "InventoryCount").</param>
    /// <param name="referenceId">Optional reference entity ID.</param>
    /// <param name="notes">Optional notes.</param>
    public static InventoryAdjustment Create(
        int adjustmentNo,
        short warehouseId,
        DateTime? adjustmentDate,
        InventoryAdjustmentType adjustmentType,
        int accountId,
        int? createdByUserId = null,
        string? reason = null,
        string? referenceType = null,
        int? referenceId = null,
        string? notes = null)
    {
        if (adjustmentNo <= 0)
            throw new DomainException("رقم التسوية مطلوب.");
        if (warehouseId <= 0)
            throw new DomainException("المستودع مطلوب.");
        if (accountId <= 0)
            throw new DomainException("حساب التسوية مطلوب.");

        var adjustment = new InventoryAdjustment
        {
            AdjustmentNo = adjustmentNo,
            WarehouseId = warehouseId,
            AdjustmentDate = adjustmentDate ?? DateTime.UtcNow,
            AdjustmentType = adjustmentType,
            AccountId = accountId,
            Reason = reason,
            ReferenceType = referenceType,
            ReferenceId = referenceId,
            Notes = notes,
            Status = InventoryCountStatus.Draft
        };
        adjustment.SetCreatedBy(createdByUserId);
        return adjustment;
    }

    /// <summary>
    /// Adds an adjustment line (product quantity and cost) to this adjustment.
    /// Only allowed when the adjustment is in Draft status.
    /// </summary>
    public void AddLine(InventoryAdjustmentLine line)
    {
        if (line == null)
            throw new DomainException("صنف التسوية مطلوب.");
        if (Status != InventoryCountStatus.Draft)
            throw new DomainException("لا يمكن إضافة أصناف لتسوية غير مسودة.");

        _lines.Add(line);
        UpdateTimestamp();
    }

    /// <summary>
    /// Posts the inventory adjustment — transitions status from Draft to Posted.
    /// Validates that at least one line exists before posting.
    /// Once posted, the adjustment is irreversible.
    /// </summary>
    public void Post(int? postedByUserId = null)
    {
        if (Status != InventoryCountStatus.Draft)
            throw new DomainException("فقط التسويات المسودة يمكن ترحيلها.");
        if (!_lines.Any())
            throw new DomainException("لا يمكن ترحيل تسوية بدون أصناف.");

        Status = InventoryCountStatus.Posted;
        PostedAt = DateTime.UtcNow;
        PostedByUserId = postedByUserId;
        UpdateTimestamp();
    }

    /// <summary>
    /// Cancels the inventory adjustment — transitions to Cancelled status.
    /// </summary>
    public void Cancel()
    {
        if (Status == InventoryCountStatus.Cancelled)
            throw new DomainException("التسوية ملغاة بالفعل.");

        Status = InventoryCountStatus.Cancelled;
        UpdateTimestamp();
    }
}
