using SalesSystem.Domain.Common;
using SalesSystem.Domain.Enums;
using SalesSystem.Domain.Exceptions;

namespace SalesSystem.Domain.Entities;

/// <summary>
/// Represents a physical inventory count session for a specific warehouse.
/// Tracks system quantities vs. actual counted quantities to identify discrepancies.
/// </summary>
public class InventoryCount : DocumentEntity
{
    public int CountNo { get; private set; }
    public DateTime CountDate { get; private set; }
    public short WarehouseId { get; private set; }
    public InventoryCountStatus Status { get; private set; }
    public string? Notes { get; private set; }
    public int? PostedByUserId { get; private set; }

    // Navigation properties
    public virtual Warehouse? Warehouse { get; private set; }
    public virtual User? PostedByUser { get; private set; }

    private readonly List<InventoryCountLine> _lines = new();
    public IReadOnlyCollection<InventoryCountLine> Lines => _lines.AsReadOnly();

    private InventoryCount() { }

    /// <summary>
    /// Creates a new inventory count session.
    /// </summary>
    /// <param name="countNo">The sequential count number (generated by DocumentSequenceService).</param>
    /// <param name="warehouseId">The warehouse being counted.</param>
    /// <param name="countDate">The date of the physical count.</param>
    /// <param name="createdByUserId">Optional ID of the user creating the count.</param>
    public static InventoryCount Create(
        int countNo,
        short warehouseId,
        DateTime? countDate = null,
        int? createdByUserId = null)
    {
        if (countNo <= 0)
            throw new DomainException("رقم الجرد مطلوب.");
        if (warehouseId <= 0)
            throw new DomainException("المستودع مطلوب.");

        var inventoryCount = new InventoryCount
        {
            CountNo = countNo,
            WarehouseId = warehouseId,
            CountDate = countDate ?? DateTime.UtcNow,
            Status = InventoryCountStatus.Draft
        };
        inventoryCount.SetCreatedBy(createdByUserId);
        return inventoryCount;
    }

    /// <summary>
    /// Adds a count line (product count record) to this inventory count session.
    /// Only allowed when the count is in Draft status.
    /// </summary>
    public void AddLine(InventoryCountLine line)
    {
        if (line == null)
            throw new DomainException("صنف الجرد مطلوب.");
        if (Status != InventoryCountStatus.Draft)
            throw new DomainException("لا يمكن إضافة أصناف لجرد غير مسودة.");

        _lines.Add(line);
        UpdateTimestamp();
    }

    /// <summary>
    /// Posts the inventory count — transitions status from Draft to Posted.
    /// Validates that at least one line exists before posting.
    /// </summary>
    public void Post(int postedByUserId)
    {
        if (Status != InventoryCountStatus.Draft)
            throw new DomainException("فقط الجرد المسودة يمكن ترحيله.");
        if (!_lines.Any())
            throw new DomainException("لا يمكن ترحيل جرد بدون أصناف.");

        Status = InventoryCountStatus.Posted;
        PostedAt = DateTime.UtcNow;
        PostedByUserId = postedByUserId;
        UpdateTimestamp();
    }

    /// <summary>
    /// Cancels the inventory count — transitions to Cancelled status.
    /// </summary>
    public void Cancel()
    {
        if (Status == InventoryCountStatus.Cancelled)
            throw new DomainException("الجرد ملغى بالفعل.");

        Status = InventoryCountStatus.Cancelled;
        UpdateTimestamp();
    }

    /// <summary>
    /// Updates the notes on this inventory count.
    /// Only allowed when in Draft status.
    /// </summary>
    public void SetNotes(string? notes)
    {
        if (Status != InventoryCountStatus.Draft)
            throw new DomainException("لا يمكن تحديث ملاحظات جرد غير مسودة.");

        Notes = notes;
        UpdateTimestamp();
    }
}
