using SalesSystem.Domain.Common;
using SalesSystem.Domain.Exceptions;

namespace SalesSystem.Domain.Entities;

/// <summary>
/// Represents a user notification generated by system events.
/// Notifications are hard-deleted after being read or archived — no IsActive flag.
/// </summary>
public class Notification : AuditableEntity
{
    /// <summary>
    /// FK to the User who receives this notification.
    /// </summary>
    public int UserId { get; private set; }

    /// <summary>
    /// Navigation property to the receiving User.
    /// </summary>
    public virtual User User { get; private set; } = null!;

    /// <summary>
    /// Notification type code (e.g. 1 = Info, 2 = Warning, 3 = Alert).
    /// </summary>
    public byte Type { get; private set; }

    /// <summary>
    /// Short notification title.
    /// </summary>
    public string Title { get; private set; } = string.Empty;

    /// <summary>
    /// Full notification message body.
    /// </summary>
    public string Message { get; private set; } = string.Empty;

    /// <summary>
    /// Whether the user has read this notification.
    /// </summary>
    public bool IsRead { get; private set; }

    /// <summary>
    /// Target recipient type: User = 1, Role = 2, Branch = 3.
    /// </summary>
    public byte RecipientType { get; private set; }

    /// <summary>
    /// Optional reference to a related entity type (e.g. "SalesInvoice").
    /// </summary>
    public string? ReferenceType { get; private set; }

    /// <summary>
    /// Optional FK to the related entity.
    /// </summary>
    public int? ReferenceId { get; private set; }

    /// <summary>
    /// When the user read this notification. Null until read.
    /// </summary>
    public DateTime? ReadAt { get; private set; }

    private Notification() { } // EF Core

    /// <summary>
    /// Factory method to create a new notification.
    /// </summary>
    /// <param name="userId">The ID of the user who will receive this notification (must be > 0).</param>
    /// <param name="type">Notification type code.</param>
    /// <param name="title">Short notification title (required, non-empty).</param>
    /// <param name="message">Full notification message (required, non-empty).</param>
    /// <param name="recipientType">Target recipient type: User = 1, Role = 2, Branch = 3. Defaults to User.</param>
    /// <param name="referenceType">Optional reference entity type (e.g. "SalesInvoice").</param>
    /// <param name="referenceId">Optional FK to the referenced entity.</param>
    /// <returns>A new Notification instance.</returns>
    /// <exception cref="DomainException">If any guard clause fails.</exception>
    public static Notification Create(
        int userId,
        byte type,
        string title,
        string message,
        byte recipientType = 1,
        string? referenceType = null,
        int? referenceId = null)
    {
        if (userId <= 0)
            throw new DomainException("معرّف المستخدم غير صالح.");
        if (string.IsNullOrWhiteSpace(title))
            throw new DomainException("عنوان الإشعار مطلوب.");
        if (string.IsNullOrWhiteSpace(message))
            throw new DomainException("نص الإشعار مطلوب.");
        if (recipientType < 1 || recipientType > 3)
            throw new DomainException("نوع المستلم غير صالح. القيم المسموحة: User=1, Role=2, Branch=3.");
        if (referenceId.HasValue && string.IsNullOrWhiteSpace(referenceType))
            throw new DomainException("نوع المرجع مطلوب عند تحديد معرّف المرجع.");

        return new Notification
        {
            UserId = userId,
            Type = type,
            Title = title.Trim(),
            Message = message.Trim(),
            IsRead = false,
            RecipientType = recipientType,
            ReferenceType = referenceType?.Trim(),
            ReferenceId = referenceId
        };
    }

    /// <summary>
    /// Marks this notification as read. Idempotent — safe to call multiple times.
    /// Sets ReadAt to the current UTC time on first read.
    /// </summary>
    public void MarkAsRead()
    {
        if (!IsRead)
        {
            IsRead = true;
            ReadAt = DateTime.UtcNow;
            UpdateTimestamp();
        }
    }

    /// <summary>
    /// Marks this notification as unread. Idempotent — safe to call multiple times.
    /// Clears ReadAt.
    /// </summary>
    public void MarkAsUnread()
    {
        if (IsRead)
        {
            IsRead = false;
            ReadAt = null;
            UpdateTimestamp();
        }
    }
}
